language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install build-essential libgl1-mesa-dev qt512base qt512multimedia qt512quickcontrols2 qt512quickcontrols qt512declarative 
  - source /opt/qt*/bin/qt*-env.sh

script:
  - qmake .
  - make -j$(nproc)
  - mkdir -p appdir/usr/bin ; strip BlueGlow ; cp BlueGlow appdir/usr/bin/
  - mkdir -p appdir/usr/share/applications ; cp BlueGlow.desktop appdir/usr/share/applications/
  - mkdir -p appdir/usr/share/icons/hicolor/256x256/apps/ ; cp resources/logo.png appdir/usr/share/icons/hicolor/256x256/apps/BlueGlow.png
  - wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
  - chmod a+x linuxdeployqt-continuous-x86_64.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - export VERSION=$(git rev-parse --short HEAD)
  - ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/*.desktop -qmldir=$(qmake -query QT_INSTALL_QML) -bundle-non-qt-libs
  - wget -c -nv "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" 
  - cp /usr/lib/x86_64-linux-gnu/libcrypt.so* appdir/usr/lib
  - cp /usr/lib/x86_64-linux-gnu/libssl.so* appdir/usr/lib
  - cp /usr/lib/x86_64-linux-gnu/libcrypto.so* appdir/usr/lib
  - chmod +x appimagetool-x86_64.AppImage
  - ./appimagetool-x86_64.AppImage -u "gh-releases-zsync|antony-jr|blue-glow|continuous|BlueGlow*-x86_64.AppImage.zsync" appdir 


after_success:
  - wget "https://github.com/probonopd/uploadtool/raw/master/upload.sh"
  - bash upload.sh BlueGlow*.AppImage *zsync
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
